a=5.0 # "Acá declaramos la variable 1"
b=4.5 # "Acá declaramos la variable 2"
c=1.0 # "Acá declaramos la variable 3"
promedio = (a+b+c)/3 # "Acá ponemos la variable promedio y hacemos la suma de las 3 variables para luego dividirlas entre 3"
print("El promedio es" , promedio) # "luego ponemos la función print para imprimir el promedio de las 3 variables"